### ISSUE TITLE
Lineup relation

### ISSUE THREAD

**Issue by eriksivertsen** [kevinsamyn/soccerama-pro-client#1]
Thanks for this.
Having issues when adding the "Lineup" relation to the parameters. This causes a exception: **no single-String constructor/factory method.**

Any idea how to solve this?

**Comment by kevinsamyn** [comment]
You're welcome.
I'll watch it.
Which proxy?

**Comment by eriksivertsen** [comment]
LivescoreProxy! Sample code:


final SocceramaAPIClient instance = SocceramaAPIClient.getInstance(settings.getProperty("SOCCERAMA_TOKEN"));
		final LivescoreProxy livescoreProxy = instance.getLivescoreProxyInstance();
		final LivescoreProxyParams params = new LivescoreProxyParams();

		params.addRelation(LivescoreProxy.Relation.events);
		params.addRelation(LivescoreProxy.Relation.homeTeam);
		params.addRelation(LivescoreProxy.Relation.awayTeam);
		params.addRelation(LivescoreProxy.Relation.season);
		 params.addRelation(LivescoreProxy.Relation.lineup);
		params.addRelation(LivescoreProxy.Relation.homeStats);
		params.addRelation(LivescoreProxy.Relation.awayStats);

livescoreProxy.findCurrentlyPlayed(params);

**Comment by kevinsamyn** [comment]
Hi,

I am unable to reproduce the anomaly. Could you send me the receipt JSON?

**Comment by eriksivertsen** [comment]
How can I print the output? Is there a debug setting etc?

Btw, do I need to use the MatchStatisticsProxyInstance to get matchstats, or could I just include the relation like i did in the example?

**Comment by kevinsamyn** [comment]
Simply call https://api.soccerama.pro/v1.1/livescore?api_token=TOKEN in your browser.

Normally you can use relations.

**Comment by eriksivertsen** [comment]
[Uploading response.txt…]()

**Comment by eriksivertsen** [comment]
[response.txt](https://github.com/kevinsamyn/soccerama-pro-client/files/410531/response.txt)

No problem at the moment, APIClient running fine (no lineups matches I guess)

**Comment by kevinsamyn** [comment]
OK, please send me json with lineups when you can.

**Comment by eriksivertsen** [comment]
[lineup.txt](https://github.com/kevinsamyn/soccerama-pro-client/files/412676/lineup.txt)

More info:
Can not instantiate value of type [simple type, class pro.soccerama.client.bean.entity.Position] from String value; no single-String constructor/factory method (through reference chain: pro.soccerama.client.bean.structure.LivescoreResponse["data"]->pro.soccerama.client.bean.entity.Match["lineup"]->pro.soccerama.client.bean.structure.MatchLineups["data"]->pro.soccerama.client.bean.entity.MatchLineup["position"])

**Comment by kevinsamyn** [comment]
Thanks, I try to fix it today.

**Comment by eriksivertsen** [comment]
Smooth! Give me a shout out when you fix it :)

**Comment by kevinsamyn** [comment]
Can you update and try again ? 

List of positions:

- Goalkeeper
- CD-L
- CD-R
- LB
- RB
- CM-L
- CM-R
- LM
- RM
- CF-L
- CF-R
- SUB

**Comment by eriksivertsen** [comment]
Works now! Thank you! (btw could you build a new jar file?)

**Comment by kevinsamyn** [comment]
You can build jar with `mvn clean install` command
