### ISSUE TITLE
NullPointerException when trying to get Competition by ID and on many other endpoints

### ISSUE THREAD

**Issue by huzvak** [kevinsamyn/soccerama-pro-client#2]
When I am trying to get a Competiton by ID (43 for Danish top league) I am getting all the time the NullPointerException. I tried also to list all the competitions, but the same result.

Only endpoint/proxy that is working is LivescoreProxy. This one is returning the data.

Is there a bug with CompetitionProxy or is it OK and problem is on my side?

Example of the code:

`
private static final SocceramaAPIClient instance = SocceramaAPIClient.getInstance(SOCCERAMA_TOKEN);
private static final int DANISH_SUPERLIGA = 43;

public static void main(String[] args) throws NotFoundException {
		CompetitionProxy compProxy = instance.getCompetitionProxyInstance();
					
		List<Competition> competitions = compProxy.findAll();
					
		for(Competition comp : competitions) {
			System.out.println("Name: " + comp.getName() + ", id: " + comp.getId() + ", active: " + comp.getActive() + 
					", country: " + comp.getCountry() + ", current season: " + comp.getCurrentSeason() + 
					", seasons: " + comp.getSeasons());
		}
					
					
		Competition danishLeague = compProxy.findOne(DANISH_SUPERLIGA);
					
		Season season = danishLeague.getCurrentSeason();
					
					
		TeamProxy teamProxy = instance.getTeamProxyInstance();
		List<Team> teams = teamProxy.findBySeason(season.getId());
			
		for (Team team : teams) {
			Venue venue = team.getVenue();
			TeamPlayers teamPlayers = team.getPlayers();
			TeamMatches teamMatches = team.getMatches();
			List<Player> players = teamPlayers.getData();
			List<Match> matches = teamMatches.getData();
						
						
			System.out.println("Team: " + team.getName() + ", logo: " + team.getLogo() + ", twitter: " + team.getTwitter() + 
					", venue: city: " + venue.getCity() + ", name: " + venue.getName());
						
			Map<String, Object> props = venue.getAdditionalProperties();
						
			System.out.println("Venue properties: ");
			for (Entry<String, Object> prop : props.entrySet()) {
				System.out.println("Key: " + prop.getKey() + ", value: " + prop.getValue());
			}
		}
	}
`

**Comment by kevinsamyn** [comment]
Hi,

Thanks for your message. I can try to correct this as soon as possible.

This is in v1.1 or v1.2 ?

Kévin

**Comment by huzvak** [comment]
Hi, 

thanks for quick response. I cloned repo today. So I guess it is v1.2

Can you please write a comment here when it is fixed (or at least close the issue)?
Thanks.

**Comment by kevinsamyn** [comment]
Can you tell me which line causes the exception?

**Comment by huzvak** [comment]
Hi, 

if I remember correctly (I am not right now at my computer), then it is this one: Competition danishLeague = compProxy.findOne(DANISH_SUPERLIGA);

**Comment by kevinsamyn** [comment]
Can you try again and tell me if is OK ?

**Comment by huzvak** [comment]
Hi, 

it looks like there are still bugs.
E.g. from my code above:

Competition danishLeague = compProxy.findOne(DANISH_SUPERLIGA);  - still throwing NullPointerException

Also when I am printing output about Competitions in for cycle: getCountry(), getCurrentSeason() and getSeasons() all return null.

Probably I will try v1.1. and will check whether it is working correctly there.
