### ISSUE TITLE
Maven Repisotory

### ISSUE THREAD

**Issue by sima-hindiyeh** [kevinsamyn/soccerama-pro-client#4]
is there like a maven directory for the library instead of having to import it? this way i can get updates easily.
Moreover I had to fix a couple of issues when i downloaded the code. For example the PlayersResponse class had "players" instead of data. and some properties are missing from some classes like the shirt_number and fullname in Player ...

**Comment by kevinsamyn** [comment]
I fixed PlayersResponse.
